on: [push, pull_request]
name: Test
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

        target: [
          aarch64-linux-gnu,
          aarch64-linux-musl,
          x86_64-linux-gnu,
          x86_64-linux-musl,
          aarch64-macos,
          x86_64-macos,
          wasm32-wasi
          x86_64-windows-gnu

          x86-linux-gnu,
          x86-linux-musl,
          x86-windows,
        ]
    runs-on: ${{ matrix.os }}
    needs: [test-x86_64-linux, test-x86_64-windows]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    # Run our go tests within the context of the dev shell from the flake. This
    # will ensure we have all our dependencies.
    - name: test
      run: zig build --summary all -Dtarget=${{ matrix.target }}

  test-x86_64-linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: master
.
    - name: test
      run: zig build test --summary all

    - name: test wasi
       run: zig build test -Dtarget=wasm32-wasi -fwasmtime --summary all

    - name: build all benchmarks and examples
      run: zig build -Dexample -Dbench --summary all

    # Run a full build to ensure that works
    #- run: nix build

  test-x86_64-windows:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: master

    - name: test
      run: zig build test --summary all

    - name: build all benchmarks and examples
      run: zig build -Dexample -Dbench --summary all
